### ISSUE TITLE
Don't Merge With Fablabnbg

### ISSUE THREAD

**Issue by KedneckInc** [lexelby/inkscape-silhouette#2]
I've been trying to use Fablabnbg's latest code, and to be quite blunt, it just doesn't work on my Curio 3.  On the other hand, YOUR code works darn near perfectly.  Just need to tune the x/y offset on the Silhouette tab to get it just right.

Keep your code separate from his, it works.

**Comment by jnweiger** [comment]
I am really happy to see all the progress going on here. I own a silhouette cameo 1, and found that the code over at fablabnbg currently does not work with that old device. One of the commits we merged were probably bad for that ancient device.
 
When comparing lexelby:nmaster against fablabnbg, github says: "This branch is 17 commits ahead, 22 commits behind fablabnbg:master. "

So the question is: is it one of the 17 commits that brings curio support, or one of the 22 commits on the fablabnbg side that breaks curio 3 support? Do we know?
In any case I see no point maintaining two separate forks. I'd like to pull as much as I can from lexelby towards fablabnbg. But even then, I cannot test curio 3, I can only re-test my old cameo 1 then.

did not check for merge conflicts yet....

Other opinions please! 
@EtherGraf ?

**Comment by EtherGraf** [comment]
I have just compared both master branches in detail. The differences aren't really that big.

The code on fablabnbg has additional support for cameo 3. I don't see any breaking change for the cameo 1. Also on fablabnbg there was added optional support for different knive diameters and another optional cutting strategy.

The code from lexelby has as its main advantage in the multi cutting extension. This is an additional feature in a separate python file and does not touch the original extension. This way it could be merged without big risks.

Only one small change from lexelby is missing in fablabnbng. It is the last commit "properly detect closed paths". All other commits have been merged already to fablabnbg.

In none of the versions I can see any support of the curio 3. Has it the same IDs as another model???

I also don't like the effort divided into two parallel forks and would recommend to merge both forks into one. I have just no idea how to achieve this the best way. Just merge pull request #45? Or apply the changes by hand?

With the upcoming ubuntu 18.04 there will soon be needs for supporting inkscape 0.92 and its different default dpi settings.

**Comment by KedneckInc** [comment]
The biggest difference between the two is that lexelby works on the Cameo 3, almost "out of the box".

I had tried lexelby first, because I do have the Cameo 3, and it does have two pen holders, so I really wanted the support for multiple colors.  It seemed to work, although there were some issues, so I decided that I'd give the last release of fablabnbg a try.

I really tried with fablabnbg and could not get it to work even minimally correctly.  The cutting would start somewhere in the middle of the 12x12 mat, and run off the right side.  By the look of it, it was expecting the image to be up against the right edge, but even moving the paper to that side of the mat I still couldn't get even a simple pattern to cut correctly.  After multiple attempts, fiddling with the adjustments, completely deleting including the configuration file, reinstalling, hair pulling, and invocation of the profanities gods, I finally gave up and went back to try lexelby again.

Lexelby mostly worked after changing the X/Y-Offsets to (6.0, 16.0).  The remaining problem with lexelby is that there's something odd with the apparent page size.  The upper left corner is correctly positioned. 
The bottom gets chopped off well short of the bottom of the paper.  This happens despite the fact that I left a 1/4 inch margin around the test pattern.  It's almost as if the software has decided that I'm not using US Letter (8.5x11in), but am using some other odd paper size.

I think that at least part of the problem is that the available documentation and/or suggestions of things to try are scattered across the web.  The instructions I found on fablabnbg just didn't seem to cover the issues I was having.  I only tonight found a reference that indicated the problem may be the DPI setting of InkScape.

If you need a guinea pig who happens to have a Cameo 3, I'd be happy to run tests for you.  Provide a test inkscape file for drawing, not cutting, and I'll try running your extension again.  We'll figure out some way to get the results back to you.  Maybe scan the results in and drop it in here?  I really would like to help, as I am getting very tired of using VirtualBox to run Windows just so I can run the official Silhouette software, which is mostly used for final integration of the graphics and the score/cutting.  The patterns are still created in Inkscape, and exported to DXF format for use in Silhouette's software.

**Comment by KedneckInc** [comment]
Ran a few more tests with lexelby, using my corners test document.  Switching to 96dpi was a very bad idea, had to switch it back to 90dpi.  I added lines on a separate layer to indicate where the sketching is cut off.  What follows is a set of four screen shots showing the corners.

The following image is the upper left corner of the document.  A series of lines two mm apart numbered from one to four repeated twice in both directions.

![screenshot from 2018-04-30 22-12-01](https://user-images.githubusercontent.com/6062168/39458778-04ecc48a-4cc5-11e8-8789-2fadb6e2bcba.png)

This pattern is repeated in each corner of the page.  The next shot is the upper right corner.  The light blue line indicates the cutoff point.  Anything that extends beyond that point is not drawn, so the two upper lines are lost, all three of the lines and numbers to the right are lost, and the part of the 4 that extends beyond the blue line is lost.
![screenshot from 2018-04-30 22-24-39](https://user-images.githubusercontent.com/6062168/39458828-803c52d6-4cc5-11e8-94ac-87b9ea473f49.png)

Now the bottom right corner.
![screenshot from 2018-04-30 22-26-59](https://user-images.githubusercontent.com/6062168/39458846-a644f9d8-4cc5-11e8-87b3-05a0c1dfe94a.png)

And the bottom left.
![screenshot from 2018-04-30 22-27-39](https://user-images.githubusercontent.com/6062168/39458856-bc6c5f9e-4cc5-11e8-9e3a-289995f00026.png)

**Comment by EtherGraf** [comment]
On the first look it looks like the offset dimensions (6mm on X and 16mm on Y axis). As far as I know comes the border limits from the document dimensions. Try to extend the document dimensions some mm.

In my setup I use the offset value (0,0) and just align the paper in the plotter.

**Comment by EtherGraf** [comment]
Sorry, if my first snetence isn't clear. It's to late today. The size of the offset seems the size of the missing elements.

**Comment by EtherGraf** [comment]
Have just found the same coordinates in the sourcecode:   

`{ 'vendor_id': 0x0b4d, 'product_id': 0x112f, 'name': 'Silhouette Cameo3',
   'width_mm':  304, 'length_mm': 3000, 'margin_left_mm':5, 'margin_top_mm':15.5, 'regmark': True },`

Do not really understand the meaning of this dimensions. Seems they are handled as an additional offset, which leads to the cutoff on the right and bottom side, as the media box doesn't grow by this values.

In the next days I have no time for further investigations, sorry.

**Comment by KedneckInc** [comment]
Well I'll be.  I hadn't noticed the correlation between the offsets (6 by 16) and the cut off.  I'll take a look at the source you reference and see if I can figure out some adjustments that work.  Thanks!

**Comment by KedneckInc** [comment]
@EtherGraf,  I owe you an apology.

I think the real difference was that Lexelby's code I installed directly from the repo.  Your code, I installed from one of the old DEB files.  This time around, I installed directly from a clone of the Fablabnbg repo, running 'make' to create a DEB with the latest code from master.

I just tried it, with offsets 6/16 and with 0/0.  The 0/0 offsets worked better.  The upper left appears exactly where it should be, the upper right is all there as well.  The only remaining problem is the bottom, which is chopped off in exactly the same place approximately 15 mm from the bottom of the actual page.

Hmmm... That would correspond with the 'margin_top_mm'  being subtracted from the bottom of the page size wouldn't it.

Again, my apologies.

**Comment by jnweiger** [comment]
@KedneckInc @EtherGraf thanks for clearing that up!
The last DEB package that is available for download is dated 19 Dec 2016, cough. My bad.
I guess we should upload a more recent one there.... :-)

Is master in a sane state currently? If so, I'd go ahead and make new DEB packages available later tonight.

**Comment by EtherGraf** [comment]
Just stumbled about https://github.com/fablabnbg/inkscape-silhouette/issues/58
This describes precise your problem. Im not convinced by the given solution,but you can try it.
I propose to close this thread.

**Comment by KedneckInc** [comment]
Just to be certain, I increased the dimensions by 20 mm in both directions. The Cameo 3 is presently drawing the path I gave it without any difficulty. I'll be trying actually cutting the page next.

Just finished now.  It's drawn the pattern exactly as I wished.  Now to try cutting it.

Perfect.  Fit exactly where I needed it to.

The only gripe with this method is that because Inkscape uses the bottom left as the origin, the page expands up and right.  That means you have to reposition your pattern to the upper left to get it come out right on the Cameo 3.

**Comment by KedneckInc** [comment]
I went looking for a solution, and came across this.

http://www.inkscapeforum.com/viewtopic.php?t=18077

I'm reluctant to try the suggestion at the bottom, as I don't know how the export works.  If it actually depends upon the existing view box of the paper, then we're stuck with the lower left corner.

As a more likely alternative to the above, setting guides on the top and left that you can snap to seems a better option.  Remains within the existing page boundaries, and makes moving the pattern easy.

Agreed, the thread can be closed.
